{% set version = "1.1.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-embed
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/embed_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/embed/embed_{{ version }}.tar.gz
  sha256: f517d6040fd5f7afaaa578b167a9f127c25dc0671111b3a8957b0f8ac835a2e8

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr
    - r-generics >=0.1.0
    - r-glue
    - r-keras
    - r-lifecycle
    - r-purrr
    - r-recipes >=0.1.17
    - r-rlang >=0.4.10
    - r-rsample
    - r-tensorflow
    - r-tibble
    - r-tidyr
    - r-uwot
    - r-withr
  run:
    - r-base
    - r-dplyr
    - r-generics >=0.1.0
    - r-glue
    - r-keras
    - r-lifecycle
    - r-purrr
    - r-recipes >=0.1.17
    - r-rlang >=0.4.10
    - r-rsample
    - r-tensorflow
    - r-tibble
    - r-tidyr
    - r-uwot
    - r-withr

test:
  commands:
    - $R -e "library('embed')"           # [not win]
    - "\"%R%\" -e \"library('embed')\""  # [win]

about:
  home: https://embed.tidymodels.org, https://github.com/tidymodels/embed
  license: MIT
  summary: Predictors can be converted to one or more numeric representations using a variety of methods. Effect encodings using simple generalized linear models <arXiv:1611.09477> or nonlinear models <arXiv:1604.06737> can be used.  There are also functions for dimension reduction and other approaches.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
